/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 살아 있는지 */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 — Access 는 본문, Refresh 는 httpOnly 쿠키 */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 재발급 — 쿠키만 보고 판단한다 */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 — 쿠키를 지운다 */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 — **권한 플래그를 서버가 내려준다** (D-R39) */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 코드표 — 수업 종류 · 과목 · 강의실 · 줌 · 구성원 · 학생 */
        get: operations["MetaController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회차 목록 — 일간·주간·월간·학생별·선생님별이 모두 이것을 쓴다 */
        get: operations["ScheduleController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/horizon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 펼쳐 둔 기간 — 화면이 「비었다」와 「아직 안 펼쳤다」를 구분한다 */
        get: operations["ScheduleController_bounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 수업 만들기 — 겹치면 DB 가 409 로 막는다 (D-R43) */
        post: operations["ScheduleController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/{serId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 수업 취소·휴강 — 참조가 있으면 지우지 않고 기간을 마감한다 */
        delete: operations["ScheduleController_remove"];
        options?: never;
        head?: never;
        /** 수업 고치기 — scope 로 이번만·향후·모두를 가른다 (D-R16) */
        patch: operations["ScheduleController_patch"];
        trace?: never;
    };
    "/schedule/{serId}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 수강 학생 넣고 빼기 — 「그날만 빼기」가 D-R21 이다 (§12 · §79) */
        patch: operations["ScheduleController_roster"];
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리포트 목록 */
        get: operations["ReportsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/unwritten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** §47 안 쓴 리포트 — 강사별 밀린 건수와 예상 차감 */
        get: operations["ReportsController_unwritten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회계 — 청구서 · 입금 · 정산. 금액은 대표만 값이 채워진다 */
        get: operations["AccountingController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영 — 상담 · 컴플레인 · 할 일 · 기획 · 회의 · 마케팅 · 건의 */
        get: operations["OpsController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consulting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 컨설팅 — 건 · 학생 · 회차 기록 (§29 · §30) */
        get: operations["ConsultingController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 수업 현황판 — 교재·안내·줌·리포트 4마크를 매번 계산한다 (§34 · D-R4) */
        get: operations["BoardController_range"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 교재 — 코드 · 과목 · 쪽수 · SE/TE (§36) */
        get: operations["BooksController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 수업 안내 — 한 번만(GUIDE) · 회차마다(PNOTI) (§41 · §42) */
        get: operations["GuidesController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 대표 보고 — 집계는 저장하지 않는다 (§69 · D-R4 · D-R39) */
        get: operations["ExecController_range"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drawer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서랍 여덟 칸을 한 번에 — 결재 5종 정규화 포함 (D-R26 · D-R34) */
        get: operations["DrawerController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drawer/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** §15 할 일 체크 — 내가 주고받은 것만 */
        patch: operations["DrawerController_todoDone"];
        trace?: never;
    };
    "/drawer/notis/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** §16 알림 읽음 */
        patch: operations["DrawerController_notiRead"];
        trace?: never;
    };
    "/drawer/change-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** §19 변경 요청 넣기 — 겹치면 **누구와** 겹치는지 돌려주고 넣지 않는다 */
        post: operations["DrawerController_createChangeReq"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example kim@tnacademy.kr */
            email: string;
            /** @example ******** */
            password: string;
        };
        MeDto: {
            id: number;
            name: string;
            /** @enum {string} */
            role: "teacher" | "manager" | "admin" | "ceo";
            /** @description 직함 — 권한과 무관 */
            title: string | null;
            /** @description 관리자 백오피스 진입 */
            canAdminPage: boolean;
            /** @description 전 항목 CRUD */
            canCrudAll: boolean;
            /** @description 지출 · 총수입 — 대표 전용 */
            canSeeProfit: boolean;
            /** @description 오늘·이전 스케줄 출결 (D-R35) */
            canCrudAttendance: boolean;
            canMoney: boolean;
            canWage: boolean;
            canApprove: boolean;
            canHide: boolean;
            canGpaPack: boolean;
        };
        LoginResultDto: {
            /** @description Access 토큰 (15분). Refresh 는 httpOnly 쿠키로 나갑니다 */
            accessToken: string;
            user: components["schemas"]["MeDto"];
        };
        RefreshResultDto: {
            accessToken: string;
        };
        KindDto: {
            key: string;
            name: string;
            /** @description 토큰과 같은 값 — 화면은 이 색을 쓰기만 한다 */
            color: string;
            cap: number;
            /** @enum {string} */
            grp: "lesson" | "intake" | "meeting";
            /** @description 리포트 대상인가 (D-4) */
            rep: boolean;
        };
        SubDto: {
            key: string;
            name: string;
            color: string;
        };
        RoomDto: {
            id: number;
            branch: string;
            name: string;
            capacity?: number | null;
        };
        ZaccDto: {
            id: number;
            label: string;
            meetingId?: string | null;
        };
        StaffBriefDto: {
            id: number;
            name: string;
            /** @enum {string} */
            role: "teacher" | "manager" | "admin" | "ceo";
            /** @description 표시용 직함 — 권한과 무관하다 (D-R39) */
            title?: string | null;
        };
        StudentBriefDto: {
            id: number;
            name: string;
            grade?: string | null;
            school?: string | null;
        };
        MetaDto: {
            kinds: components["schemas"]["KindDto"][];
            subs: components["schemas"]["SubDto"][];
            rooms: components["schemas"]["RoomDto"][];
            zaccs: components["schemas"]["ZaccDto"][];
            staff: components["schemas"]["StaffBriefDto"][];
            students: components["schemas"]["StudentBriefDto"][];
        };
        OccStudentDto: {
            id: number;
            name: string;
            grade?: string | null;
            /** @description 그날만 빠진 학생인가 (D-R21) */
            droppedOnce: boolean;
        };
        OccurrenceDto: {
            /** @description 반복 규칙 id */
            serId: number;
            /**
             * @description 화면에 그려질 날짜
             * @example 2026-08-28
             */
            date: string;
            /**
             * @description 규칙상 원래 날짜 — **EXC 의 키**다. 쓰기(PATCH·DELETE)는 이 값으로 회차를 찾는다
             * @example 2026-08-28
             */
            onDate: string;
            /** @description 자정부터 분 */
            startMin: number;
            endMin: number;
            kindKey: string;
            subKey?: string | null;
            title?: string | null;
            teacherId?: number | null;
            teacherName?: string | null;
            roomId?: number | null;
            roomName?: string | null;
            zaccId?: number | null;
            /** @enum {string} */
            mode: "offline" | "online";
            canceled: boolean;
            /** @description 이 회차에 예외가 붙었는가 */
            hasException: boolean;
            /**
             * @description 리포트 상태. 캘린더 블록 색이 이 값에서 나온다 (D-R7 · V26 §2.3)
             * @enum {string}
             */
            repState: "na" | "plan" | "none" | "draft" | "wait" | "ok" | "rej";
            /** @description 리포트를 썼는가 — 정산에 들어가는 조건 하나 (D-R7) */
            written: boolean;
            students: components["schemas"]["OccStudentDto"][];
        };
        OccurrenceListDto: {
            /** @example 2026-08-24 */
            from: string;
            /** @example 2026-08-30 */
            to: string;
            items: components["schemas"]["OccurrenceDto"][];
        };
        HorizonDto: {
            /** @description 펼쳐 둔 기간의 시작 */
            from: string;
            /** @description 펼쳐 둔 기간의 끝 */
            to: string;
            /** @description 요청 범위가 이 밖으로 나갔는가 — 화면이 「비었다」와 「아직 안 펼쳤다」를 구분한다 */
            clamped: boolean;
        };
        OccurrenceCreateDto: {
            kindKey: string;
            subKey?: string | null;
            /** @enum {string} */
            mode: "offline" | "online";
            /** @description 첫 회차 날짜 */
            fromDate: string;
            /** @description 없으면 열린 반복 */
            toDate?: string | null;
            /** @description ONCE | DAILY[/n] | WEEKLY:MO,WE[/n] — formatRule() 이 정한 형식만 받는다 */
            rrule: string;
            startMin: number;
            endMin: number;
            teacherId?: number | null;
            roomId?: number | null;
            title?: string | null;
            /** @description 정식 명단 */
            studentIds?: number[];
        };
        WriteResultDto: {
            /** @description 실제로 적용된 범위 — 「향후」가 「모두」로 강등되면 여기서 드러난다 (D-R17) */
            effScope: string;
            /** @description 사람이 읽는 변경 기록. 화면이 그대로 보여 준다 */
            log: string[];
            /** @description 다시 펼친 회차 수 */
            projected: number;
            /** @description 영향받은 규칙 — 화면은 이 범위만 다시 읽으면 된다 */
            serIds: number[];
        };
        OccurrencePatchDto: {
            /**
             * @description 이번만 · 향후 · 모두 (D-R16). 첫 회차의 future 는 all 로 강등된다 (D-R17)
             * @enum {string}
             */
            scope: "this" | "future" | "all";
            /** @description 규칙상 원래 날짜 — EXC 의 키다. 옮긴 회차도 이 값으로 찾는다 */
            onDate: string;
            /** @description 0~1439 */
            startMin?: number | null;
            endMin?: number | null;
            teacherId?: number | null;
            roomId?: number | null;
            /** @description 다른 날로 옮길 때만 */
            date?: string | null;
            reason?: string | null;
        };
        OccurrenceDeleteDto: {
            /** @enum {string} */
            scope: "this" | "future" | "all";
            onDate: string;
        };
        RosterPatchDto: {
            /** @enum {string} */
            op: "add" | "dropOnce" | "undoOnce" | "dropAll";
            onDate: string;
            studentId: number;
        };
        ReportStudentDto: {
            id: number;
            name: string;
            grade?: string | null;
        };
        ReportRowDto: {
            id: number;
            serId: number;
            /** @example 2026-08-27 */
            date: string;
            startMin: number;
            subKey?: string | null;
            kindKey: string;
            teacherId?: number | null;
            teacherName?: string | null;
            /** @enum {string} */
            state: "na" | "plan" | "none" | "draft" | "wait" | "ok" | "rej";
            /** @description 썼는가 — 정산 조건 (D-R7) */
            written: boolean;
            students: components["schemas"]["ReportStudentDto"][];
            /** @description 수업이 끝난 뒤 지난 분. 음수면 아직 안 끝났다 */
            minutesSinceEnd: number;
            /** @description 지금 확정하면 깎이는 금액 (D-R32) */
            penalty: number;
        };
        ReportListDto: {
            items: components["schemas"]["ReportRowDto"][];
        };
        UnwrittenByTeacherDto: {
            teacherId: number;
            teacherName: string;
            count: number;
            /** @description 가장 오래된 것 */
            oldestDate?: string | null;
            /** @description 1시간 넘긴 건수 */
            over1h: number;
            /** @description 4시간 넘긴 건수 */
            over4h: number;
            /** @description 예상 차감 합계 */
            penalty: number;
        };
        UnwrittenDto: {
            byTeacher: components["schemas"]["UnwrittenByTeacherDto"][];
            total: number;
            penaltyTotal: number;
            items: components["schemas"]["ReportRowDto"][];
        };
        MoneySummaryDto: {
            invoiceCount: number;
            billed: number | null;
            collected: number | null;
            outstanding: number | null;
            overdueCount: number;
            /** @description 금액을 볼 수 있는가 (D-R39 · 사람별 예외까지 반영된 canMoney) */
            canSeeAmounts: boolean;
        };
        InvoiceLineDto: {
            subKey?: string | null;
            label: string;
            count: number;
            unitPrice: number;
            amount: number;
        };
        InvoiceDto: {
            id: number;
            studentId: number;
            studentName: string;
            grade?: string | null;
            yearMonth: string;
            title: string;
            /** @description 금액 — canMoney 가 아니면 null 로 내려간다 (D-R39) */
            amount: number | null;
            paidAmount: number | null;
            /** @enum {string} */
            state: "draft" | "sent" | "unpaid" | "partial" | "paid" | "void";
            issuedOn?: string | null;
            dueOn?: string | null;
            paidAt?: string | null;
            /** @description 예정일이 지났는데 안 들어온 날 수. 0이면 연체 아님 */
            overdueDays: number;
            lines: components["schemas"]["InvoiceLineDto"][];
        };
        PaymentDto: {
            id: number;
            paidOn: string;
            studentId?: number | null;
            studentName?: string | null;
            amount: number | null;
            method?: string | null;
            invId?: number | null;
        };
        PayoutDto: {
            id: number;
            staffId: number;
            staffName: string;
            yearMonth: string;
            hours: string;
            gross: number | null;
            /** @description 리포트 지연 차감 (D-R32) */
            lateRepCut: number | null;
            incomeTax: number | null;
            localTax: number | null;
            net: number | null;
            state: string;
        };
        AccountingDto: {
            summary: components["schemas"]["MoneySummaryDto"];
            invoices: components["schemas"]["InvoiceDto"][];
            payments: components["schemas"]["PaymentDto"][];
            payouts: components["schemas"]["PayoutDto"][];
        };
        LeadDto: {
            id: number;
            name: string;
            school?: string | null;
            /** @description first | wait2nd | second | hold | enrolled | failed */
            stage: string;
            ownerName?: string | null;
            /** @description 실패한 경우 어디서 멈췄나 (§24) */
            stopAt?: string | null;
            reason?: string | null;
            createdAt: string;
            /** @description 접수한 지 며칠 */
            ageDays: number;
        };
        ComplaintDto: {
            id: number;
            /** @enum {string} */
            area: "lesson" | "intake" | "book" | "schedule" | "teacher";
            studentName?: string | null;
            /** @description received | acting | closed */
            stage: string;
            body: string;
            action?: string | null;
            result?: string | null;
            createdAt: string;
            ageDays: number;
        };
        TodoDto: {
            id: number;
            title: string;
            toName?: string | null;
            dueOn?: string | null;
            done: boolean;
            /** @enum {string} */
            src: "meeting" | "complaint" | "consulting" | "plan" | "manual";
            /** @description 기한이 지난 날 수. 0이면 안 지남 */
            overdueDays: number;
        };
        PlanDto: {
            id: number;
            title: string;
            /** @description draft | review | rework | approved | done */
            stage: string;
            goal?: string | null;
            ask?: string | null;
            dueOn?: string | null;
            ownerName?: string | null;
            overdueDays: number;
        };
        MeetingDto: {
            id: number;
            mtType: string;
            title?: string | null;
            onDate?: string | null;
            attendees: number;
            confirmed: number;
            /** @description 속기록을 썼는가 — 안 쓰면 회의가 끝난 것이 아니다 */
            hasMinutes: boolean;
        };
        MarketingDto: {
            id: number;
            channel: string;
            item: string;
            url?: string | null;
            impressions?: number | null;
            clicks?: number | null;
            inquiries?: number | null;
            enrolled?: number | null;
            /** @description 집행 비용 — 대표만 (D-R39) */
            cost?: number | null;
            /** @description 등록당 비용 */
            costPerEnroll?: number | null;
        };
        SuggestionDto: {
            id: number;
            staffName: string;
            /** @enum {string} */
            category: "lesson" | "pay" | "schedule" | "etc";
            body: string;
            /** @enum {string} */
            state: "open" | "reviewing" | "done";
            reply?: string | null;
            createdAt: string;
        };
        OpsDto: {
            leads: components["schemas"]["LeadDto"][];
            complaints: components["schemas"]["ComplaintDto"][];
            todos: components["schemas"]["TodoDto"][];
            plans: components["schemas"]["PlanDto"][];
            meetings: components["schemas"]["MeetingDto"][];
            marketing: components["schemas"]["MarketingDto"][];
            suggestions: components["schemas"]["SuggestionDto"][];
            /** @description 집행 비용을 볼 수 있는가 */
            canSeeAmounts: boolean;
        };
        ConsultingSessionDto: {
            id: number;
            /** @description 몇 번째 회차 */
            seq: number;
            onDate: string;
            who?: string | null;
            what?: string | null;
            why?: string | null;
            how?: string | null;
            /** @description 연결된 수업이 있으면 그 SER */
            serId?: number | null;
        };
        ConsultingDto: {
            id: number;
            /**
             * @description 종류 10종 중 시드에 있는 것
             * @enum {string}
             */
            consType: "admissions" | "essay" | "roadmap";
            /**
             * @description 계약 → 진행 → 종료
             * @enum {string}
             */
            stage: "contract" | "running" | "done";
            /** @description 계약 5단계 — 계약서 → 피드백 → 학부모 전달 → 서명본 → 수납 */
            contractStep?: number | null;
            studentNames: string[];
            ownerName?: string | null;
            sessions?: number | null;
            endOn?: string | null;
            createdAt: string;
            /** @description 대표가 아니면 null */
            amount?: number | null;
            /**
             * @description 전체 공개 · 수납만 공개 · 지정 공개 · 전체 비공개
             * @enum {string}
             */
            share: "all" | "money_only" | "picked" | "private";
            /** @description 내용(회차 기록)을 열 수 있는가 — csCanFull() */
            canOpen: boolean;
            sessionsLog: components["schemas"]["ConsultingSessionDto"][];
        };
        ConsultingListDto: {
            items: components["schemas"]["ConsultingDto"][];
            /** @description 금액을 볼 수 있는가 (D-R39) */
            canSeeAmounts: boolean;
        };
        CheckMarkDto: {
            /** @enum {string} */
            key: "book" | "guide" | "zoom" | "report";
            /** @description 지금 이 순간의 판정 */
            done: boolean;
            /** @description 해당 없음이면 판정하지 않는다 — 오프라인 수업의 줌 같은 것 */
            na: boolean;
            /** @description 왜 이렇게 판정했는지 한 줄 */
            note?: string | null;
        };
        BoardRowDto: {
            occId: number;
            serId: number;
            onDate: string;
            /** @description HH:MM */
            startAt: string;
            /** @description HH:MM */
            endAt: string;
            teacherName?: string | null;
            roomName?: string | null;
            /** @enum {string} */
            mode: "offline" | "online";
            kindKey: string;
            kindName?: string | null;
            studentNames: string[];
            canceled: boolean;
            /** @description 교재 · 안내 · 줌 · 리포트 */
            marks: components["schemas"]["CheckMarkDto"][];
            /** @description 판정 대상 중 덜 된 개수. 0이면 다 됐다 */
            missing: number;
        };
        BoardDto: {
            from: string;
            to: string;
            rows: components["schemas"]["BoardRowDto"][];
            /** @description 덜 된 수업 수 — 화면 위 배지 */
            missingCount: number;
            /** @description 저장하지 않는다는 사실을 화면이 그대로 적을 수 있게 (D-R4) */
            computedAt: string;
        };
        BookDto: {
            /** @description 교재 코드 — 카드에 그대로 보인다 */
            code: string;
            id: number;
            title: string;
            subKey?: string | null;
            subName?: string | null;
            level?: string | null;
            grade?: string | null;
            pages?: number | null;
            /** @description SE 학생용 · TE 교사용 */
            seTe?: string | null;
        };
        BooksDto: {
            items: components["schemas"]["BookDto"][];
            /** @description 과목별 권수 — 필터 칩에 쓴다 */
            bySub: {
                [key: string]: number;
            };
        };
        GuideDto: {
            id: number;
            /** @description new(첫 수업) | teacher_change(강사 교체) */
            reason: string;
            /**
             * @description draft·ready 가 아직 안 보낸 것
             * @enum {string}
             */
            state: "draft" | "ready" | "sent" | "read";
            studentName?: string | null;
            teacherName?: string | null;
            serTitle?: string | null;
            body?: string | null;
            dueOn?: string | null;
            createdAt: string;
            /** @description 기한이 지난 날 수. 0이면 안 지남 */
            overdueDays: number;
        };
        PerLessonNoticeDto: {
            id: number;
            onDate: string;
            /** @enum {string} */
            channel: "sms" | "kakao" | "email" | "app";
            studentName?: string | null;
            serTitle?: string | null;
            body: string;
            /** @description 아직 안 보냈으면 null */
            sentAt?: string | null;
        };
        GuidesDto: {
            /** @description 한 번만 나가는 안내 */
            guides: components["schemas"]["GuideDto"][];
            /** @description 회차마다 나가는 안내 */
            perLesson: components["schemas"]["PerLessonNoticeDto"][];
            /** @description 아직 안 보낸 안내 수 */
            todoCount: number;
            /** @description 강사면 자기 것만 본다 — 그 강사 id */
            scopedTeacherId?: number | null;
        };
        ExecStatDto: {
            key: string;
            label: string;
            /** @description 볼 권한이 없으면 null (D-R39) */
            value?: number | null;
            unit?: string | null;
            /** @description 금액이라 권한을 타는 칸인가 */
            money: boolean;
        };
        ExecReportDto: {
            id: number;
            /** @enum {string} */
            rptType: "day" | "week" | "month";
            onDate: string;
            /**
             * @description **RPT(대표 보고)의 낱말**이다. 수업 리포트(REP)의 rep_state_t 와 다르다 — 한동안 그것을 적어 두어 실제로 내려가는 sent 가 목록에 없었다
             * @enum {string}
             */
            state: "draft" | "sent" | "ok" | "rej";
            /** @description D-R14 — 한 줄이라도 적어야 제출된다. jsonb 의 note 를 꺼내 문자열로 내린다 */
            memo: string;
            sentAt?: string | null;
            reviewedAt?: string | null;
            /** @description D-R13 — 반려(rej)하면 사유가 반드시 있다 */
            rejectReason?: string | null;
        };
        ExecDto: {
            from: string;
            to: string;
            stats: components["schemas"]["ExecStatDto"][];
            reports: components["schemas"]["ExecReportDto"][];
            /** @description 금액을 볼 수 있는가 (D-R39) */
            canSeeAmounts: boolean;
            /** @description 저장하지 않는다 — 이 시각에 센 값이다 (D-R4) */
            computedAt: string;
        };
        ApRowDto: {
            /** @enum {string} */
            kind: "rpt" | "plan" | "req" | "chreq" | "gpapack";
            id: number;
            title: string;
            sub?: string | null;
            byId?: number | null;
            byName?: string | null;
            at: string;
            /** @enum {string} */
            state: "waiting" | "back" | "done";
            /** @description 반려면 반드시 있다 (D-R13) */
            why?: string | null;
            /** @description 누르면 갈 곳 — 오버레이에서 승인하지 않는다 (D-R27) */
            go: string;
        };
        ApFlowDto: {
            /** @description 되돌아온 것 — 맨 위 (§75) */
            back: components["schemas"]["ApRowDto"][];
            /** @description 기다리는 것 */
            waiting: components["schemas"]["ApRowDto"][];
            /** @description 내가 올린 것 */
            mine: components["schemas"]["ApRowDto"][];
            /** @description 배지 숫자 — 손이 가야 하는 것만 센다 */
            count: number;
            /** @description 아직 표가 없어 못 세는 갈래 (N-13 대기) */
            missingKinds: string[];
        };
        DrawerTodoDto: {
            id: number;
            title: string;
            fromName?: string | null;
            toName?: string | null;
            fromId?: number | null;
            toId?: number | null;
            dueOn?: string | null;
            done: boolean;
            /** @enum {string} */
            src: "meeting" | "complaint" | "consulting" | "plan" | "manual";
            /** @description 기한이 지난 날 수. 0이면 안 지남 */
            overdueDays: number;
            /** @description 출처가 있으면 원본으로 갈 곳 */
            go?: string | null;
        };
        NotiDto: {
            id: number;
            body: string;
            fromName?: string | null;
            toId?: number | null;
            link?: string | null;
            read: boolean;
            at: string;
            /**
             * @description 표에 색 컬럼이 없어 링크로 파생한다 — lib/noti.ts 한 곳에서만
             * @enum {string}
             */
            tone: "alarm" | "ok" | "warn";
        };
        MemberDto: {
            id: number;
            name: string;
            email: string;
            /** @enum {string} */
            role: "teacher" | "manager" | "admin" | "ceo";
            /** @description 직함은 권한이 아니다 (D-R39) */
            title?: string | null;
            tz?: string | null;
            active: boolean;
        };
        TzGroupDto: {
            id: number;
            name: string;
            tz: string;
        };
        KindRowDto: {
            key: string;
            name: string;
            color: string;
            /** @description 정원 */
            cap: number;
            /** @enum {string} */
            grp: "lesson" | "intake" | "meeting";
            /** @description true 인 종류만 리포트 대상 (D-R6) */
            rep: boolean;
        };
        ChangeReqDto: {
            id: number;
            /** @enum {string} */
            reqType: "wage_change" | "unav_add" | "doc" | "time" | "time_move" | "teacher" | "room" | "off" | "cancel";
            serId?: number | null;
            onDate?: string | null;
            reason?: string | null;
            state: string;
            byName?: string | null;
            /** @description 정기 수업이면 이후 전체 적용 */
            applyAll: boolean;
            at: string;
        };
        ZoomAccountDto: {
            id: number;
            label: string;
            /** @description 학생 참가 링크. 로그인 정보와 같은 화면에 두지 않는다 */
            joinUrl?: string | null;
            active: boolean;
            /** @description 이 계정이 잡고 있는 회차 수 */
            assigned: number;
            /** @description 같은 시간에 두 수업에 배정된 건수 — 0이어야 한다 */
            overlaps: number;
        };
        DrawerDto: {
            /** @description §14 승인 대기함 */
            approvals: components["schemas"]["ApFlowDto"];
            /** @description §15 할 일 */
            todos: components["schemas"]["DrawerTodoDto"][];
            /** @description §16 알림 */
            notis: components["schemas"]["NotiDto"][];
            /** @description §17 구성원 */
            members: components["schemas"]["MemberDto"][];
            /** @description §17 시간대 그룹 */
            tzGroups: components["schemas"]["TzGroupDto"][];
            /** @description §18 수업 종류 */
            kinds: components["schemas"]["KindRowDto"][];
            /** @description §20 변경 요청 */
            changeReqs: components["schemas"]["ChangeReqDto"][];
            /** @description §21 줌 계정 */
            zoomAccounts: components["schemas"]["ZoomAccountDto"][];
            /** @description 관리자 화면의 모든 시각은 KST 다 (D-R12) */
            tz: string;
        };
        TodoDoneDto: {
            /** @description 완료로 바꿀지 여부 */
            done: boolean;
        };
        ChangeReqCreateDto: {
            /**
             * @description 수업을 바꿔 달라는 요청의 종류
             * @enum {string}
             */
            reqType: "time_move" | "teacher" | "room" | "cancel";
            /** @description 어느 수업인지 */
            serId?: number;
            /**
             * @description 어느 날짜인지
             * @example 2026-09-01
             */
            onDate?: string;
            /** @description 바꾸려는 내용 — 종류에 따라 startMin · endMin · teacherId · roomId · zaccId */
            payload?: {
                [key: string]: unknown;
            };
            /** @description 사유는 비워 둘 수 없다 (D-R13 과 같은 이유) */
            reason: string;
            /** @description 정기 수업이면 이후 전체 적용 (D-R16) */
            applyAll?: boolean;
        };
        ConflictRowDto: {
            serId: number;
            onDate: string;
            startMin: number;
            endMin: number;
            title?: string | null;
            /**
             * @description 무엇이 겹치는가
             * @enum {string}
             */
            with: "teacher" | "room" | "zoom";
            /** @description 누구와 겹치는가 — 이름을 보여 준다 */
            whoName?: string | null;
        };
        ChangeReqResultDto: {
            /** @description 만들어진 요청 id. 겹쳐서 막혔으면 없다 */
            id?: number | null;
            /** @description 비어 있지 않으면 제출이 막힌 것이다 */
            conflicts: components["schemas"]["ConflictRowDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResultDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResultDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    MetaController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaDto"];
                };
            };
        };
    };
    ScheduleController_list: {
        parameters: {
            query: {
                from: string;
                to: string;
                teacherId?: string;
                studentId?: string;
                roomId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccurrenceListDto"];
                };
            };
        };
    };
    ScheduleController_bounds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorizonDto"];
                };
            };
        };
    };
    ScheduleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccurrenceCreateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultDto"];
                };
            };
        };
    };
    ScheduleController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccurrenceDeleteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultDto"];
                };
            };
        };
    };
    ScheduleController_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccurrencePatchDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultDto"];
                };
            };
        };
    };
    ScheduleController_roster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterPatchDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultDto"];
                };
            };
        };
    };
    ReportsController_list: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                teacherId?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListDto"];
                };
            };
        };
    };
    ReportsController_unwritten: {
        parameters: {
            query?: {
                teacherId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnwrittenDto"];
                };
            };
        };
    };
    AccountingController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingDto"];
                };
            };
        };
    };
    OpsController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsDto"];
                };
            };
        };
    };
    ConsultingController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultingListDto"];
                };
            };
        };
    };
    BoardController_range: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardDto"];
                };
            };
        };
    };
    BooksController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooksDto"];
                };
            };
        };
    };
    GuidesController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidesDto"];
                };
            };
        };
    };
    ExecController_range: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecDto"];
                };
            };
        };
    };
    DrawerController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawerDto"];
                };
            };
        };
    };
    DrawerController_todoDone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoDoneDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DrawerController_notiRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DrawerController_createChangeReq: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeReqCreateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeReqResultDto"];
                };
            };
        };
    };
}
