/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 살아 있는지 */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 — Access 는 본문, Refresh 는 httpOnly 쿠키 */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 재발급 — 쿠키만 보고 판단한다 */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 — 쿠키를 지운다 */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 — **권한 플래그를 서버가 내려준다** (D-R39) */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 코드표 — 수업 종류 · 과목 · 강의실 · 줌 · 구성원 · 학생 */
        get: operations["MetaController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회차 목록 — 일간·주간·월간·학생별·선생님별이 모두 이것을 쓴다 */
        get: operations["ScheduleController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리포트 목록 */
        get: operations["ReportsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/unwritten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** §47 안 쓴 리포트 — 강사별 밀린 건수와 예상 차감 */
        get: operations["ReportsController_unwritten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회계 — 청구서 · 입금 · 정산. 금액은 대표만 값이 채워진다 */
        get: operations["AccountingController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영 — 상담 · 컴플레인 · 할 일 · 기획 · 회의 · 마케팅 · 건의 */
        get: operations["OpsController_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example kim@tnacademy.kr */
            email: string;
            /** @example ******** */
            password: string;
        };
        MeDto: {
            id: number;
            name: string;
            /** @enum {string} */
            role: "teacher" | "manager" | "admin" | "ceo";
            /** @description 직함 — 권한과 무관 */
            title: string | null;
            /** @description 관리자 백오피스 진입 */
            canAdminPage: boolean;
            /** @description 전 항목 CRUD */
            canCrudAll: boolean;
            /** @description 지출 · 총수입 — 대표 전용 */
            canSeeProfit: boolean;
            /** @description 오늘·이전 스케줄 출결 (D-R35) */
            canCrudAttendance: boolean;
            canMoney: boolean;
            canWage: boolean;
            canApprove: boolean;
            canHide: boolean;
            canGpaPack: boolean;
        };
        LoginResultDto: {
            /** @description Access 토큰 (15분). Refresh 는 httpOnly 쿠키로 나갑니다 */
            accessToken: string;
            user: components["schemas"]["MeDto"];
        };
        RefreshResultDto: {
            accessToken: string;
        };
        KindDto: {
            key: string;
            name: string;
            /** @description 토큰과 같은 값 — 화면은 이 색을 쓰기만 한다 */
            color: string;
            cap: number;
            /** @enum {string} */
            grp: "lesson" | "intake" | "meeting";
            /** @description 리포트 대상인가 (D-4) */
            rep: boolean;
        };
        SubDto: {
            key: string;
            name: string;
            color: string;
        };
        RoomDto: {
            id: number;
            branch: string;
            name: string;
            capacity?: number | null;
        };
        ZaccDto: {
            id: number;
            label: string;
            meetingId?: string | null;
        };
        StaffBriefDto: {
            id: number;
            name: string;
            /** @enum {string} */
            role: "teacher" | "manager" | "admin" | "ceo";
            /** @description 표시용 직함 — 권한과 무관하다 (D-R39) */
            title?: string | null;
        };
        StudentBriefDto: {
            id: number;
            name: string;
            grade?: string | null;
            school?: string | null;
        };
        MetaDto: {
            kinds: components["schemas"]["KindDto"][];
            subs: components["schemas"]["SubDto"][];
            rooms: components["schemas"]["RoomDto"][];
            zaccs: components["schemas"]["ZaccDto"][];
            staff: components["schemas"]["StaffBriefDto"][];
            students: components["schemas"]["StudentBriefDto"][];
        };
        OccStudentDto: {
            id: number;
            name: string;
            grade?: string | null;
            /** @description 그날만 빠진 학생인가 (D-R21) */
            droppedOnce: boolean;
        };
        OccurrenceDto: {
            /** @description 반복 규칙 id */
            serId: number;
            /** @example 2026-08-28 */
            date: string;
            /** @description 자정부터 분 */
            startMin: number;
            endMin: number;
            kindKey: string;
            subKey?: string | null;
            title?: string | null;
            teacherId?: number | null;
            teacherName?: string | null;
            roomId?: number | null;
            roomName?: string | null;
            zaccId?: number | null;
            /** @enum {string} */
            mode: "offline" | "online";
            canceled: boolean;
            /** @description 이 회차에 예외가 붙었는가 */
            hasException: boolean;
            /**
             * @description 리포트 상태. 캘린더 블록 색이 이 값에서 나온다 (D-R7 · V26 §2.3)
             * @enum {string}
             */
            repState: "na" | "plan" | "none" | "draft" | "wait" | "ok" | "rej";
            /** @description 리포트를 썼는가 — 정산에 들어가는 조건 하나 (D-R7) */
            written: boolean;
            students: components["schemas"]["OccStudentDto"][];
        };
        OccurrenceListDto: {
            /** @example 2026-08-24 */
            from: string;
            /** @example 2026-08-30 */
            to: string;
            items: components["schemas"]["OccurrenceDto"][];
        };
        ReportStudentDto: {
            id: number;
            name: string;
            grade?: string | null;
        };
        ReportRowDto: {
            id: number;
            serId: number;
            /** @example 2026-08-27 */
            date: string;
            startMin: number;
            subKey?: string | null;
            kindKey: string;
            teacherId?: number | null;
            teacherName?: string | null;
            /** @enum {string} */
            state: "na" | "plan" | "none" | "draft" | "wait" | "ok" | "rej";
            /** @description 썼는가 — 정산 조건 (D-R7) */
            written: boolean;
            students: components["schemas"]["ReportStudentDto"][];
            /** @description 수업이 끝난 뒤 지난 분. 음수면 아직 안 끝났다 */
            minutesSinceEnd: number;
            /** @description 지금 확정하면 깎이는 금액 (D-R32) */
            penalty: number;
        };
        ReportListDto: {
            items: components["schemas"]["ReportRowDto"][];
        };
        UnwrittenByTeacherDto: {
            teacherId: number;
            teacherName: string;
            count: number;
            /** @description 가장 오래된 것 */
            oldestDate?: string | null;
            /** @description 1시간 넘긴 건수 */
            over1h: number;
            /** @description 4시간 넘긴 건수 */
            over4h: number;
            /** @description 예상 차감 합계 */
            penalty: number;
        };
        UnwrittenDto: {
            byTeacher: components["schemas"]["UnwrittenByTeacherDto"][];
            total: number;
            penaltyTotal: number;
            items: components["schemas"]["ReportRowDto"][];
        };
        MoneySummaryDto: {
            invoiceCount: number;
            billed: number | null;
            collected: number | null;
            outstanding: number | null;
            overdueCount: number;
            /** @description 금액을 볼 수 있는가 (D-R39 canSeeProfit) */
            canSeeAmounts: boolean;
        };
        InvoiceLineDto: {
            subKey?: string | null;
            label: string;
            count: number;
            unitPrice: number;
            amount: number;
        };
        InvoiceDto: {
            id: number;
            studentId: number;
            studentName: string;
            grade?: string | null;
            yearMonth: string;
            title: string;
            /** @description 금액 — canSeeProfit 이 아니면 null 로 내려간다 (D-R39) */
            amount: number | null;
            paidAmount: number | null;
            /** @enum {string} */
            state: "draft" | "sent" | "unpaid" | "partial" | "paid" | "void";
            issuedOn?: string | null;
            dueOn?: string | null;
            paidAt?: string | null;
            /** @description 예정일이 지났는데 안 들어온 날 수. 0이면 연체 아님 */
            overdueDays: number;
            lines: components["schemas"]["InvoiceLineDto"][];
        };
        PaymentDto: {
            id: number;
            paidOn: string;
            studentId?: number | null;
            studentName?: string | null;
            amount: number | null;
            method?: string | null;
            invId?: number | null;
        };
        PayoutDto: {
            id: number;
            staffId: number;
            staffName: string;
            yearMonth: string;
            hours: string;
            gross: number | null;
            /** @description 리포트 지연 차감 (D-R32) */
            lateRepCut: number | null;
            incomeTax: number | null;
            localTax: number | null;
            net: number | null;
            state: string;
        };
        AccountingDto: {
            summary: components["schemas"]["MoneySummaryDto"];
            invoices: components["schemas"]["InvoiceDto"][];
            payments: components["schemas"]["PaymentDto"][];
            payouts: components["schemas"]["PayoutDto"][];
        };
        LeadDto: {
            id: number;
            name: string;
            school?: string | null;
            /** @description first | wait2nd | second | hold | enrolled | failed */
            stage: string;
            ownerName?: string | null;
            /** @description 실패한 경우 어디서 멈췄나 (§24) */
            stopAt?: string | null;
            reason?: string | null;
            createdAt: string;
            /** @description 접수한 지 며칠 */
            ageDays: number;
        };
        ComplaintDto: {
            id: number;
            /** @enum {string} */
            area: "lesson" | "intake" | "book" | "schedule" | "teacher";
            studentName?: string | null;
            /** @description received | acting | closed */
            stage: string;
            body: string;
            action?: string | null;
            result?: string | null;
            createdAt: string;
            ageDays: number;
        };
        TodoDto: {
            id: number;
            title: string;
            toName?: string | null;
            dueOn?: string | null;
            done: boolean;
            /** @enum {string} */
            src: "meeting" | "complaint" | "consulting" | "plan" | "manual";
            /** @description 기한이 지난 날 수. 0이면 안 지남 */
            overdueDays: number;
        };
        PlanDto: {
            id: number;
            title: string;
            /** @description draft | review | rework | approved | done */
            stage: string;
            goal?: string | null;
            ask?: string | null;
            dueOn?: string | null;
            ownerName?: string | null;
            overdueDays: number;
        };
        MeetingDto: {
            id: number;
            mtType: string;
            title?: string | null;
            onDate?: string | null;
            attendees: number;
            confirmed: number;
            /** @description 속기록을 썼는가 — 안 쓰면 회의가 끝난 것이 아니다 */
            hasMinutes: boolean;
        };
        MarketingDto: {
            id: number;
            channel: string;
            item: string;
            url?: string | null;
            impressions?: number | null;
            clicks?: number | null;
            inquiries?: number | null;
            enrolled?: number | null;
            /** @description 집행 비용 — 대표만 (D-R39) */
            cost?: number | null;
            /** @description 등록당 비용 */
            costPerEnroll?: number | null;
        };
        SuggestionDto: {
            id: number;
            staffName: string;
            /** @enum {string} */
            category: "lesson" | "pay" | "schedule" | "etc";
            body: string;
            /** @enum {string} */
            state: "open" | "reviewing" | "done";
            reply?: string | null;
            createdAt: string;
        };
        OpsDto: {
            leads: components["schemas"]["LeadDto"][];
            complaints: components["schemas"]["ComplaintDto"][];
            todos: components["schemas"]["TodoDto"][];
            plans: components["schemas"]["PlanDto"][];
            meetings: components["schemas"]["MeetingDto"][];
            marketing: components["schemas"]["MarketingDto"][];
            suggestions: components["schemas"]["SuggestionDto"][];
            /** @description 집행 비용을 볼 수 있는가 */
            canSeeAmounts: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResultDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResultDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    MetaController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaDto"];
                };
            };
        };
    };
    ScheduleController_list: {
        parameters: {
            query: {
                from: string;
                to: string;
                teacherId?: string;
                studentId?: string;
                roomId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccurrenceListDto"];
                };
            };
        };
    };
    ReportsController_list: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                teacherId?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListDto"];
                };
            };
        };
    };
    ReportsController_unwritten: {
        parameters: {
            query?: {
                teacherId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnwrittenDto"];
                };
            };
        };
    };
    AccountingController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingDto"];
                };
            };
        };
    };
    OpsController_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsDto"];
                };
            };
        };
    };
}
